### ISSUE TITLE
deletion bug

### ISSUE THREAD

**Issue by NSTAdventure** [MobileFirstLLC/irregular-expressions#122]
**Describe the bug**
bruh why deletion text leave ? before totally deleted!

**To Reproduce**
1.  type a single word or msg with any style
2. then try to delete it with irregular keyboard
3. deletion leave ? mark before is completely deleted (Bruh 🗿🗿🗿🗿🗿 that's annoying)

**Expected behavior**
text should completely deleted

**Android version**
10 

**Additional context**
confused? okay i will add video demonstration

**Comment by NA0341** [comment]
ℂ𝕝𝕒𝕣𝕚𝕗𝕚𝕔𝕒𝕥𝕚𝕠𝕟 & 𝔻𝕖𝕥𝕒𝕚𝕝𝕤

The bug:
Advanced UTF-8 Symbols get only half deleted, leaving inv�lid characters behind. This doesn't happen on any other keyboard I've tried (not even the dead old Hacker's Keyboard) -> therefore it can be considered a real bug in the deletion mechanism.

This should be considered as high priority as it's a very annoying bug which directly interferes with the UX.

I'm not a developer - but as long as this isn't a bug within the core part of the application, it shouldn't be hard to fix it.

Thank You for this awesome little tool 😊

⪩ 𝓑𝓮𝓵𝓪 ⪨ ~ NA0341

**Comment by NA0341** [comment]
**This is a duplicate issue!**
Any information to the bug should be posted in #16 instead!

**Comment by NSTAdventure** [comment]
> **This is a duplicate issue!** Any information to the bug should be posted in #16 instead!

My apologies either i not search them carefully or i can't found it due to search index such problem 

Closed!
