### ISSUE TITLE
(𝙁𝙚𝙖𝙩𝙪𝙧𝙚 𝙍𝙚𝙦𝙪𝙚𝙨𝙩) 𝘋𝘷𝘰𝘳𝘢𝘬 𝘒𝘦𝘺𝘣𝘰𝘢𝘳𝘥 𝘓𝘢𝘺𝘰𝘶𝘵

### ISSUE THREAD

**Issue by shouyou10** [MobileFirstLLC/irregular-expressions#43]
Will it be possible to add 𝗗𝘃𝗼𝗿𝗮𝗸 keyboard layout? Currently to use 𝗗𝘃𝗼𝗿𝗮𝗸 layout, I have to switch to another keyboard. But I want to keep using 𝗜𝗿𝗿𝗲𝗴𝘂𝗹𝗮𝗿 𝗘𝘅𝗽𝗿𝗲𝘀𝘀𝗶𝗼𝗻 with 𝗗𝘃𝗼𝗿𝗮𝗸 layout.

**Comment by nkrusch** [comment]
Adding this here for reference: [Dvorak](https://en.wikipedia.org/wiki/Dvorak_keyboard_layout)
