### ISSUE TITLE
Option to change keyboard size

### ISSUE THREAD

**Issue by nkrusch** [MobileFirstLLC/irregular-expressions#8]
"Higher keys would be great"

**Comment by nkrusch** [comment]
options: short (mid-short) normal (mid-tall) tall

Short keys (MIN)
![img](https://i.imgur.com/zMaoz62.png)

Tall keys (MAX)
![img](https://i.imgur.com/6KuFMsg.png)

**Comment by nkrusch** [comment]
Got multiple requests for this feature

**Comment by Atrate** [comment]
Would be nice if the user could specify the height manually 𝕒𝕤 𝕨𝕖𝕝𝕝

**Comment by nkrusch** [comment]
"Great app! Please add an option for customization of the size or an option to make it a floating keyboard, it's quite small compared to other keyboards so the keys are in the lower part of the screen and I would always struggle reaching down. Thank you"
