### ISSUE TITLE
App crashes directly after start

### ISSUE THREAD

**Issue by dasdirksche** [MobileFirstLLC/irregular-expressions#98]
App crashes directly after start

**To Reproduce**
1. Click on App symbol
2. App opens a second, than crash

**Android version**
LineageOS 18.1 

**App version**
2.6.0

**Comment by nkrusch** [comment]
Please upgrade to 2.6.1, I have fixed it [here](https://github.com/MobileFirstLLC/irregular-expressions/issues/96)

**Comment by dasdirksche** [comment]
Sorry, I'm just a normal user. Where can I download the apk of 2.6.1?

02.08.2021 01:58:26 Neea Rusch ***@***.***>:

**Comment by nkrusch** [comment]
OK, no worries. You can get it on [Google play](https://play.google.com/store/apps/details?id=mf.asciitext.lite) or [download APK here on Github](https://github.com/MobileFirstLLC/irregular-expressions/releases/tag/2.6.1). It will get to F-droid soon, but it takes a bit longer to show up. I expect it to show up on F-droid at the end of this week.

**Comment by dasdirksche** [comment]
Thanks a lot

02.08.2021 19:29:27 Neea Rusch ***@***.***>:
